### ISSUE TITLE
对.xls文件的判断return false

### ISSUE THREAD

**Issue by czhaoli** [okonet/attr-accept#15]
https://github.com/okonet/attr-accept/blob/2847ab8c065ee41092f012c8a5b61e84263c815f/src/index.js#L21，
.xls文件的file.type为空字符串，
.xls允许的accept为application/vnd.ms-excel，
这样导致.xls文件返回false

**Comment by okonet** [comment]
Sorry I don’t understand that language. Issues not in English will be closed.

**Comment by okonet** [comment]
Also no need to file multiple issues.

**Comment by okonet** [comment]
That’s not a support forum. If you have question, please ask them on StackOverflow.
