### ISSUE TITLE
Allow accepting text/*

### ISSUE THREAD

**Issue by agrcrobles** [okonet/attr-accept#4]
I will need attr-accept to allow handle csv.

**Comment by okonet** [comment]
I don't think this a valid mime type. But you can use the extension, can't you?

**Comment by agrcrobles** [comment]
which extension are you meaning? not sure if I am right but I think that ie. text/plain is a valid mime type.

**Comment by agrcrobles** [comment]
oh you mean *.csv extension? not sure if possible, is it?
