### ISSUE TITLE
accept="*" should always return true

### ISSUE THREAD

**Issue by pubkey** [okonet/attr-accept#8]
```accept="*"``` should always return true. Currently it returns false.

**Comment by okonet** [comment]
> accept="*" should always return true

Can you reference to a standard that describes that behavior? MDN says:

> The value must be a comma-separated list of unique content type specifiers:
> * A valid MIME type with no extensions
> * `audio/*` representing sound files
> * `video/*` representing video files
> * `image/*` representing image files

Ref: http://mdn.beonex.com/en/HTML/Element/input.html
